---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-v1
  template:
    metadata:
      labels:
        app: payment-v1
        version: v1
    spec:
      containers:
      - name: payment
        image: to-be-replaced-by-jenkins
        env: 
        - name: DT_TAGS
          value: "product=sockshop"
        - name: DT_CUSTOM_PROP
          value: "SERVICE_TYPE=BACKEND"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 400m
            memory: 64Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
      imagePullSecrets:
      - name: proddeploycred
---
apiVersion: v1
kind: Service
metadata:
  name: payment-v1
  labels:
    app: payment-v1
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: payment-v1
