stages:
    - build
    - image

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
maven-build:
    stage: build
    image: maven:3.3.9-jdk-8-alpine
    script:
        - mvn -B clean package
    artifacts:
        paths:
            - "/builds/ACLUser2.0/carts/target/"

docker-buildnpush:
    dependencies:
        - maven-build
    stage: image
    image: docker:24.0.5
    services:
        - name: docker:24.0.5-dind
          variables:
            HEALTHCHECK_TCP_PORT: "2376"
    before_script:
        - docker info
    script:
        - docker build -t $docker_registry/carts .
        - docker push $docker_registry/carts
    artifacts:
        paths:
            - "/builds/ACLUser2.0/carts/"